name: Smiles Monitor

on:
  schedule:
    - cron: "0 */6 * * *"  # roda a cada 6 horas
  workflow_dispatch:        # permite rodar manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Telegram
      run: python telegram_test.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
