name: Smiles Monitor

on:
  schedule:
    - cron: "0 */3 * * *"   # roda a cada 3 horas
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ORIGIN: ${{ secrets.ORIGIN }}
          DESTINATIONS: ${{ secrets.DESTINATIONS }}
          START_DATE: ${{ secrets.START_DATE }}
          DAYS_RANGE: ${{ secrets.DAYS_RANGE }}
        run: python smiles_monitor.py

      - name: Upload JSON debug
        uses: actions/upload-artifact@v4
        with:
          name: smiles-debug
          path: last_response_*.json
