name: Run Smiles Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and system deps
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ORIGIN: ${{ secrets.ORIGIN }}   # opcional
          DESTINATION: ${{ secrets.DESTINATION }} # opcional
          DATE: ${{ secrets.DATE }} # opcional
        run: |
          python smiles_scraper.py || true

      - name: Upload debug artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: smiles-scraper-debug
          path: |
            no_*_found_page.png
            no_*_found_frame_*.html
            *_page.png
            *_page.html
            *_frame_*.html
            debug_*.png
            debug_*.html
