name: Run scraper

on:
  schedule:
    - cron: "0 9 * * *" # executa todo dia às 9h UTC (~6h da manhã no Brasil)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        run: python smiles_scraper.py
